cmake_minimum_required(VERSION 3.10)
find_path(helloIncludeDir hello.h ${PROJECT_SOURCE_DIR}/include)
find_library(helloLibrary NAMES hello PATH ${PROJECT_SOURCE_DIR}/lib)
if(helloIncludeDir and helloLibrary)
    set(helloFound true) 
endif(helloIncludeDir and helloLibrary)
if(helloFound)
    if(not HELLO_FIND_QUIETLY)
        message(STATUS "Found Hello:${helloLibrary}")
    endif(not HELLO_FIND_QUIETLY)
else(helloFound)
    if(HELLO_FIND_REQUIRED)
    message(FATAL_ERROR "Could not Found Hello Lib")
    endif(HELLO_FIND_REQUIRED)
        
endif(helloFound)
